### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by dweinstein** [ucsb-seclab/android_broken_fingers#1]
```
± cat /tmp/log | python postprocessing.py - | gist
Traceback (most recent call last):
  File "postprocessing.py", line 65, in <module>
    main("stdin", sys.stdin)
  File "postprocessing.py", line 55, in main
    print "--->", res['meta']['pname'], f['name'], f['value'], f['result'], "location:", f['location'], "extra:", repr(f['extra']), "sslice:", sslice
UnicodeEncodeError: 'ascii' codec can't encode character u'\u02c7' in position 40: ordinal not in range(128)
```

```
± python --version
Python 2.7.10
```

**Comment by antoniobianchi333** [comment]
Can you send me your file /tmp/log?

Have you tried running
`python postprocessing.py /tmp/log`
?

**Comment by antoniobianchi333** [comment]
I was not able to reproduce this issue.
Anyway, e729e049b1d5f44fd2d15d517bee0e321e6d7314 should fix it.

Please let me know if you still have this issue.

**Comment by antoniobianchi333** [comment]
I was able to reproduce the issue by changing the locale (`... | LC_ALL=C ./postprocessing.py  -`).
I confirm that e729e04 fixes the issue.
